In [ ]:
Numpy的数组对象：ndarray

In [ ]:
Numpy是一个开源的python科学计算器

功能：主要是用来操作数组和矩阵

数据类型：ndarray(N-dimensional array)
矩阵里必须都是同类型的数

array



- 字符串和列表乘法表示复制

In [4]:
import numpy as np

a = [1,2,3,4,5,6]
print(a)
a * 2

[1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [7]:
a = [1,2,3,4]
b = []
for i in range(len(a)):
    b.append(a[i]*2)
print(b)

[2, 4, 6, 8]


In [9]:
import numpy as np

a1 = np.array([1,2,3,4])
b1 = a1 * 2

print(b1)

[2 4 6 8]


# 2.2 ndarray对象的属性

In [14]:
import numpy as np

a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a2.ndim)      #维度数量
print(a2.shape)     #（n行,m列）
print(a2.size)      # n * m
print(a2.dtype)     #对象元素类型
print(a2.itemsize)  #以字节为单位的数组每个元素大小

2
(3, 3)
9
int32
4


- 非同质

In [6]:
import numpy as np

a3 = np.array([[1,2,3,4,5,6],[7,8,9]])  #可以由非同质对象组成

print(a3.shape)     #（n行,m列）
print(a3.size)      # n * m
print(a3.dtype)     #元素为对象类型
print(a3.itemsize)  #以字节为单位的数组每个元素大小

(2,)
2
object
8


- 可以通过修改数组的shape属性，在保持数组元素个数不变的情况下，改变数组轴的属性

In [13]:
import numpy as np

y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(y)
y.shape = 4,3       #只改变轴大小，没有改变数组元素在内存中的位置
print(y)
y.shape = 2, -1      #当某个轴为-1时系统自动计算此轴的长度
print(y)
y1 = y.reshape(4,3)  #可以使用reshape创建一个改变尺寸的新数组，保证原数组不变
print(y1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## ndarray数组的创建

In [4]:
# 1. 从python中的列表、元组等类型创建ndarray数组
import numpy as np

x1 = np.array([0,1,2,3])         # 列表类型创建
print(x1)

x2 = np.array((4,5,6,7))         # 元组类型创建
print(x2)

x3 = np.array([[8,9],(10,11)])   #列表和元组混合类型创建
print(x3)

[0 1 2 3]
[4 5 6 7]
[[ 8  9]
 [10 11]]


In [12]:
# 2. 使用numpy中函数创建ndarray数组
import numpy as np

x = np.empty([2,3])    #创建二行三列的数组
print(x)

x1 = np.ones((2,3,4))  # 创建二维三行四列数组
print(x1)

x2 = np.zeros_like(x1) #创建和x相同格式且元素全为0的数组
print(x2)

[[  4.84184333e-322   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]]
[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [13]:
x3 = np.logspace(0,2,10)  # 起值：10^0  终值：10^2  产生10个元素
print(x3)

[   1.            1.66810054    2.7825594     4.64158883    7.74263683
   12.91549665   21.5443469    35.93813664   59.94842503  100.        ]


# 转换为ndarray类型

In [24]:
import numpy as np

a = np.array([1,2,3,4,5])

print(a.dtype)

a.astype(np.float32)

int32


array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)

In [9]:
# 数乘运算，不再复制
np.array([a]) * 2

array([[ 2,  4,  6,  8, 10, 12]])

# 创建多维数组

In [11]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
dim     3维
size    9
shape  一层 3 * 3

In [ ]:
nd

In [ ]:
查类型：np.dtype

In [ ]:
d.shape
reshape

# numpy基础之数组创建

empty
zeros
zeros_like
ones
ones_like
eye 单位矩阵

In [ ]:
c = np.empty

In [15]:
d = np.zeros_like(b)
print(d)

[[0 0 0]
 [0 0 0]]


In [16]:
print(np.eye(5),dtype)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [ ]:
array类似于range函数
inspace

## 数组的索引和切片

- 一维数组的索引和切片

In [44]:
a = np.array([1,9,9,3,1,0,1,5])

print(a[2])   #索引
print(a[4:])
print(a[1:-1:2])

a[0:4] = 0,8,0,4 #通过下标修改元素的值
a

9
[1 0 1 5]
[9 3 0]


array([0, 8, 0, 4, 1, 0, 1, 5])

- <font color = 'blue'>注：与python列表不同的是，下标范围获取的数组是原数组的一个视图，所以<font color = 'red'>通过下标修改数组也修改了原数组</font></font>


In [45]:
a = np.array([1,9,9,3,1,0,1,5])

b = a[0:4]
b[:] = 0,8,0,4
a

array([0, 8, 0, 4, 1, 0, 1, 5])

- 使用整数序列对数组元素进行修改时，原数组不变

In [50]:
a = np.array([1,9,9,3,1,0,1,5])

b = a[[0,1,2,3]]
b[:] = 0,8,0,4
a

array([1, 9, 9, 3, 1, 0, 1, 5])

In [64]:
a = np.array([1,9,9,3,1,0,1,5])

# 索引
b = a[np.array([False, True, False, True, False, True, False, True])] = 1,9,9,3 
a

array([1, 1, 9, 9, 1, 9, 1, 3])

2. 多维数组的索引

In [76]:
# 索引
a = np.arange(24).reshape((2,3,4))
print(a)
a[1,2,3]   # 返回一维二行三列的数，下标从0开始

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


23

In [78]:
# 切片
a[:, 1, 3]

array([ 7, 19])

# numpy之广播

In [11]:
a = np.array([[10,10,10],[20,20,20]])
b = np.array([1,2,3])                 # b会根据a广播成[[1,2,3],[1,2,3]]

print(a*b) 
print(a+b)

[[10 20 30]
 [20 40 60]]
[[11 12 13]
 [21 22 23]]


In [1]:
import numpy as np
np.arange(0,60,10).reshape(-1,1)+np.arange(0,5) #将数组倒置再与另一数组相加

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [6]:
np.arange(0,60,10)+ np.arange(0,6) #不将数组倒置便按位相加

array([ 0, 11, 22, 33, 44, 55])

# numpy之数组的操作

#  一、反转操作
- np.reshape(order = 'C','F','A')
C：简单来说就是横着读，横着写
F：竖着读，竖着写
A：如果原数组a按照F存储的话，生成效果为F；否则为C
- np.ndarray.flatten()
- np.ndarray.T()

In [5]:
import numpy as np

a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(a)

b = a.reshape(4,3)
print(b)

b1 = a.reshape(4,3,order='F')
print(b1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]
[[ 1  5  9]
 [ 4  8  4]
 [ 7  3  7]
 [ 2  6 10]]


- np.ndarray.flat  生成迭代器
- np.ndarray.flatten

常用order{'C','F'}

In [3]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
c = a.flatten()
print(c)
c1 = a.flatten(order = 'F')
print(c1)

[ 1  2  3  4  4  5  6  7  7  8  9 10]
[ 1  4  7  2  5  8  3  6  9  4  7 10]


In [4]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(a)
print(a.T)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]


# 连接操作
- np.concatenate()
- np.stack()
- np.vstack()
- np.hstack()

In [6]:
# np.concatenate()
# axis = 0 行
# axis = 1 列
a = np.arange(6).reshape(2,3)
b = np.array([[7,8,9],[10,11,12]])

print(np.concatenate((a,b)))
print('-------我是分割线---------')
print(np.concatenate((a,b),axis = 1))

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
-------我是分割线---------
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [16]:
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.array([[7,8,9],[10,11,12]])

print(np.stack((a,b),axis = 0))      #沿着0轴（行）堆叠矩阵
print('-------我是分割线---------')
print(np.stack((a,b),axis = 1))      #沿着1轴（列）堆叠矩阵

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]
-------我是分割线---------
[[[ 0  1  2]
  [ 7  8  9]]

 [[ 3  4  5]
  [10 11 12]]]


In [18]:
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.array([[7,8,9],[10,11,12]])

print(np.hstack((a,b))) # == np.concatenate((a,b),axis = 1)    列变宽==长胖,作用于列

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [11]:
import numpy as np
#np. h/v + stack
#np.hstack((a,b))  #长胖横向
#np.vstack((a,b))  #长高纵向
a = np.arange(6).reshape(2,3)
b = np.array([[7,8,9],[10,11,12]])

print(np.vstack((a,b))) # == np.concatenate((a,b),axis = 0)    行变高==长高,作用于行
print('-------我是分割线---------')
print(np.hstack((a,b))) # == np.concatenate((a,b),axis = 1)    列变宽==长胖,作用于列


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
-------我是分割线---------
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


# 分割操作
- np.split()
- np.vsplit()
- np.hsplit()

In [21]:

# np.split()  axis 为分割方向，默认为0
import numpy as np

a = np.arange(12)
b = np.split(a,3)   #等量分成三份，前提保证能被整除
print(b)


[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [27]:
b1 = np.split(a,[4,7])    #从索引4和7处分割（包括开始元素，不包括结束元素）
print(b1)
print('-----------我是分割线------------')
b2 = np.split(a,[0,4,7])  #切完是4段，0前面为空
print(b2)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10, 11])]
-----------我是分割线------------
[array([], dtype=int32), array([0, 1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10, 11])]


In [32]:
# np.hsplit()

a = np.arange(16).reshape(4,4) 
print(a)

print('-----------我是分割线------------')
b = np.hsplit(a,2)   #从第二列分开
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------我是分割线------------
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [33]:
a = np.arange(16).reshape(4,4) 
print(a)

print('-----------我是分割线------------')
b1 = np.vsplit(a,2)  #从第二行分开
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------我是分割线------------
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# 其他操作
- np.resize()
- np.append()
- np.insert()
- np.delete()
- np.unique()

In [70]:
# np.resize(arr, new_shape)

a = np.arange(10).reshape(2,5)
b = np.resize(a,(3,4))         #转换成3行4列的矩阵
print(b)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]


In [43]:
# np.append()
a = np.arange(10).reshape(2,5)
b = np.append(a,[10,11,12])    #不给axis插成一条龙   #[1,2,3,4,5,6,7,8,9,10,11,12]
print(b)

print('-----------我是分割线------------')
b1 = np.append(a,[[10,11,12,13,14]],axis = 0)   #作用于行
print(b1)  

print('-----------我是分割线------------')
b2 = np.append(a,[[10,11,12],[13,14,15]],axis = 1)   #作用于列
print(b2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
-----------我是分割线------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------我是分割线------------
[[ 0  1  2  3  4 10 11 12]
 [ 5  6  7  8  9 13 14 15]]


In [48]:
# np.insert(arr, obj, values, axis)

a = np.array([[1,2],[3,4],[5,6]])
print(a)

print('-----------我是分割线------------')
b = np.insert(a,2,[8,9])        #未传入axis参数，展开成一维数组[1,2,8,9,3,4,5,6,7]
print(b1)

print('-----------我是分割线------------')
b1 = np.insert(a,1,[8,9],axis = 0)     #作用于行
print(b1)

print('-----------我是分割线------------')
b2 = np.insert(a,1,[7,8,9],axis = 1)   #作用于列
print(b2)

[[1 2]
 [3 4]
 [5 6]]
-----------我是分割线------------
[[1 2]
 [8 9]
 [3 4]
 [5 6]]
-----------我是分割线------------
[[1 2]
 [8 9]
 [3 4]
 [5 6]]
-----------我是分割线------------
[[1 7 2]
 [3 8 4]
 [5 9 6]]


In [52]:
# np.delete()

a = np.arange(12).reshape(3,4)
print(a)

print('-----------我是分割线------------')
b = np.delete(a,6)                          #未给axis展开为一位数组， [0.1.2.3.4.5.7.8.9.10.11]
print(b)

print('-----------我是分割线------------')
b1 = np.delete(a,2,axis = 0)                #删除第二行
print(b1)

print('-----------我是分割线------------')
b2 = np.delete(a,1,axis = 1)                #删除第二列
print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------我是分割线------------
[ 0  1  2  3  4  5  7  8  9 10 11]
-----------我是分割线------------
[[0 1 2 3]
 [4 5 6 7]]
-----------我是分割线------------
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [57]:
# np.unique()  去重并排序（从小到大）后输出
a = np.array([1,2,3,3,4,5,5,6,7,7,7,8,9,0])

b = np.unique(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
